### ISSUE TITLE
require('moonvulkan') doesn't work

### ISSUE THREAD

**Issue by WarpspeedSCP** [stetre/moonvulkan#1]
When I tried the library out, this error came up:
    `[string "require('moonvulkan.constructors')"]:1: module 'moonvulkan.constructors' not found:

    no field package.preload['moonvulkan.constructors']

    no file '/home/warpspeedscp/.luarocks/share/lua/5.1/moonvulkan/constructors.lua'

    no file '/home/warpspeedscp/.luarocks/share/lua/5.1/moonvulkan/constructors/init.lua'

    no file '/home/warpspeedscp/torch/install/share/lua/5.1/moonvulkan/constructors.lua'

    no file '/home/warpspeedscp/torch/install/share/lua/5.1/moonvulkan/constructors/init.lua'

    no file './moonvulkan/constructors.lua'

    no file '/home/warpspeedscp/torch/install/share/luajit-2.1.0-beta1/moonvulkan/constructors.lua'

    no file '/usr/local/share/lua/5.1/moonvulkan/constructors.lua'

    no file '/usr/local/share/lua/5.1/moonvulkan/constructors/init.lua'

    no file '/home/warpspeedscp/torch/install/lib/moonvulkan/constructors.so'

    no file '/home/warpspeedscp/.luarocks/lib/lua/5.1/moonvulkan/constructors.so'

    no file '/home/warpspeedscp/torch/install/lib/lua/5.1/moonvulkan/constructors.so'

    no file './moonvulkan/constructors.so'

    no file '/usr/local/lib/lua/5.1/moonvulkan/constructors.so'

    no file '/usr/local/lib/lua/5.1/loadall.so'

    no module 'moonvulkan.constructors' in file './moonvulkan.so'

    stack traceback:

    [C]: in ?

    [C]: in function 'require'

    stdin:1: in main chunk

    [C]: in ?`

Is there a fix for this?

**Comment by stetre** [comment]
Hi, MoonVulkan requires Lua 5.3, while from your logs it seems to me that you are using Lua 5.1.

**Comment by WarpspeedSCP** [comment]
hmm but I ran it with the lua 5.3 executable that I compiled along with it...

**Comment by stetre** [comment]
Are you sure? According to your logs it searches for modules in paths containing '5.1' instead of '5.3'.
MoonVulkan by default installs its Lua modules in `/usr/local/share/lua/5.3` and its C modules in `/usr/local/lib/lua/5.3`, which are pretty standard locations.

Try executing `$ lua -v` to see if the version is actually >= 5.3.
If the version is correct, check your `LUA_PATH` and `LUA_CPATH` environment variables and make sure that the above paths are included.

**Comment by WarpspeedSCP** [comment]
It seems my lua path and cpath aren't properly defined. I'll see if I can fix it, thank you.
