### ISSUE TITLE
Can't use create_swapchain()

### ISSUE THREAD

**Issue by EmperorPenguin18** [stetre/moonvulkan#7]
When trying to use the create_swapchain function I get the error `vkCreateSwapchainKHR address not loaded`. This kind of seems like a linking error, but I'm still learning Lua so I don't know.

**Comment by stetre** [comment]
Did you enable the VK_KHR_swapchain extension when creating the device?

**Comment by EmperorPenguin18** [comment]
Yes I did

**Comment by stetre** [comment]
The extension not being enabled is the most likely cause. May be a misspelled name? Unfortunately with Lua you wouldn't catch such an error directly (e.g. if you misspelled 'enabled_extension_names' or "VK_KHR_swapchain").

Can you try the [swapchain creation example](https://github.com/stetre/moonvulkan/blob/ff7fc6644e703150a713a9c8575b20eca08fb655/examples/vulkan-tutorial/06_swap_chain_creation.lua) of the vulkan-tutorial, to see if it works on your machine?

**Comment by EmperorPenguin18** [comment]
The error happens if enabled extension names is set to a variable:
```
deviceExtensions = { "VK_KHR_swapchain" }
...
enabled_extension_names = deviceExtensions
```
But not when it is set directly:
```
enabled_extension_names = { "VK_KHR_swapchain" }
```
Is this expected behaviour?

**Comment by stetre** [comment]
They should work exactly the same, provided deviceExtension is in scope and unchanged when you assign it to the enabled_extension_names field.

**Comment by EmperorPenguin18** [comment]
Thank you for your help, the problem is I'm just a Lua noob. Earlier in the code I set one table equal to deviceExtensions and remove elements from that table. I thought it would copy but turns out it is a reference and it was removing from deviceExtensions as well. Anyways problem solved!
